postMerge :
  preRun: 
    command:
      - pnpm install
      - pnpm install jest -w
      - pnpm install jest-config -w
  
  subModules:          #Not to be changed
        
      - name: hoppscotch-js-sandbox       
        path : "./"
        pattern: 
          - "./packages/hoppscotch-js-sandbox/src/__tests__/**/*.*.ts"
        
        framework : jest
        
          
        postRun:
            command:
              - node --version
        configFile : "./packages/hoppscotch-js-sandbox/jest.config.js"
        
preMerge : 
  
  subModules:          #Not to be changed
      - name: hoppscotch-cli      #Can be changed
        path : "./"
        pattern: 
          - "./packages/hoppscotch-cli/src/__tests__/**/*.*.ts"
        
        framework : jest
        postRun:
            command:
              - node --version
        
      - name: hoppscotch-js-sandbox       
        path : "./"
        pattern: 
          - "./packages/hoppscotch-js-sandbox/src/__tests__/**/*.*.ts"
        
        framework : jest
          
        postRun:
            command:
              - node --version
        configFile : "./packages/hoppscotch-js-sandbox/jest.config.js"
        
  
parallelism: 2 # this will be depricated in future
version : 2.0
