postMerge :
  preRun: 
    command:
      - pnpm install --shamefully-hoist=true 
      - cp ./packages/hoppscotch-app/.env.example ./packages/hoppscotch-app/.env
  
  subModules:          #Not to be changed
      
      - name: hoppscotch-app      
        path : "./packages/hoppscotch-app/"
        pattern: 
          - "./**/__tests__/**/*.spec.js"
        
        framework : jest
        
            
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.js"
      
        
      - name: hoppscotch-cli      
        path : "./packages/hoppscotch-cli/"
        pattern: 
          - "./src/__tests__/**/*.spec.ts"
        
        framework : jest
        
        preRun:
          command:
            - npm run prepublish
            - npm run do-typecheck
        
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.ts"
        
      - name: hoppscotch-js-sandbox     
        path : "./packages/hoppscotch-js-sandbox/"
        pattern: 
          - "./src/__tests__/**/*.spec.ts"
        
        framework : jest
        
        
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.js" 
        
        
        
preMerge : 

  preRun: 
    command:
      - pnpm install --shamefully-hoist=true 
      - cp ./packages/hoppscotch-app/.env.example ./packages/hoppscotch-app/.env

  subModules:          #Not to be changed
      - name: hoppscotch-app      
        path : "./packages/hoppscotch-app/"
        pattern: 
          - "./**/__tests__/**/*.spec.js"
        
        framework : jest
        
            
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.js"
      
        
      - name: hoppscotch-cli      
        path : "./packages/hoppscotch-cli/"
        pattern: 
          - "./src/__tests__/**/*.spec.ts"
        
        framework : jest
        
        preRun:
          command:
            - npm run prepublish
            - npm run do-typecheck
        
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.ts"
        
      - name: hoppscotch-js-sandbox     
        path : "./packages/hoppscotch-js-sandbox/"
        pattern: 
          - "./src/__tests__/**/*.spec.ts"
        
        framework : jest
        
        
        postRun:
            command:
              - node --version 
        configFile : "./jest.config.js"
        
  
version : 2.0.2
nodeVersion: 16.15.0
tier: medium




